apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: keycloak
  name: keycloak
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: keycloak
  namespace: keycloak
spec:
  vaultAuthRef: keycloak
  mount: kvv2
  type: kv-v2
  path:  keycloak
  refreshAfter: 30s
  destination:
    create: true
    name: keycloak
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: keycloak
  namespace: keycloak
spec:
  method: kubernetes
  mount: cert-manager
  kubernetes:
    role: keycloak
    serviceAccount: keycloak
    audiences:
      - vault

