
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
spec:
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 8123
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: home-assistant
subsets:
- addresses:
  - ip: 192.168.1.192
  ports:
  - name: app
    port: 8123
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: home-assistant
  annotations:
    cert-manager.io/cluster-issuer: cloudflare
spec:
  rules:
  - host: ha.technomancery.com
    http:
      paths:
      - backend:
          service:
            name: home-assistant
            port: 
              number: 80
        pathType: Prefix
        path: /
  tls:
  - hosts:
    - ha.technomancery.com
    secretName: home-assistant-tls
