apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cert-manager
    server: {{ .Values.spec.destination.server }}
  source:
    path: cert-manager
    repoURL: https://github.com/AlecMMiller/home-stack
    targetRevision: HEAD
  project: default
