apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  home-assistant
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: apps
    server: {{ .Values.spec.destination.server }}
  source:
    path: home-assistant
    repoURL: https://github.com/AlecMMiller/home-stack
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
