apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloak
    server: {{ .Values.spec.destination.server }}
  sources:
    - chart: keycloak
      repoURL: registry-1.docker.io/bitnamicharts
      targetRevision: 24.*.*
      helm:
        valueFiles:
        - $values/keycloak/values.yaml
    - repoURL: https://github.com/AlecMMiller/home-stack
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated: {}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name:  keycloak-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloak
    server: {{ .Values.spec.destination.server }}
  source:
    path: keycloak-secret
    repoURL: https://github.com/AlecMMiller/home-stack
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated: {}
