apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  ignoreDifferences:
    - group: apps
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
  sources:
    - chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.*.*
      helm:
        valueFiles:
        - $values/vault/values.yaml
    - repoURL: https://github.com/AlecMMiller/home-stack
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated: {}
