apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  sources:
    - chart: vault-secrets-operator
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 0.*.*
      helm:
        valueFiles:
        - $values/vault-operator/values.yaml
    - repoURL: https://github.com/AlecMMiller/home-stack
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    automated: {}
