server:
  ingress:
    annotations:
      cert-manager.io/issuer: cloudflare
    enabled: true
    hosts:
      - host: hv.technomancery.com
        paths: []
    tls: 
      - secretName: vault-tls
        hosts:
        - hv.technomancery.com

ui:
  enabled: true
