apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: argocd
  name: argocd-oidc
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-oidc
  namespace: argocd
spec:
  vaultAuthRef: cloudflare-api-token
  mount: kvv2
  type: kv-v2
  path:  oidc/argocd
  refreshAfter: 30s
  destination:
    create: true
    name: argocd-oidc
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: argocd-oidc
  namespace: cert-manager
spec:
  method: kubernetes
  mount: cert-manager
  kubernetes:
    role: oidc
    serviceAccount: argocd-oidc
    audiences:
      - vault

