global:
  domain: argo.technomancery.com
server:
  insecure: true
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: cloudflare
    tls: true
crds:
  install: true
  keep: true
  annotations: {}
