apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: "alecmichaelmiller@gmail.com"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cloudflare-issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token
spec:
  vaultAuthRef: cloudflare-api-token
  mount: secret
  type: kv-v2
  path:  cert-manager/cloudflare-api-token
  destination:
    create: true
    name: cloudflare-api-token-secret
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  method: kubernetes
  mount: cert-manager
  kubernetes:
    role: role1
    serviceAccount: cert-issuer
    audiences:
      - vault

